---
title: Augmented Urban Space Modeling Lab @ York University
timezone: America/New_York
collections:
  members:
    output: true
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:year/:title/"
  recruitment:
    output: true
    permalink: "/recruitment/:year/:month/:day/:title/"
  uploads:
    output: true
name: Augmented Urban Space Modeling Lab
institute: York University
location: York University, Toronto, Canada
permalink: pretty
