---
title: Augmented Urban Space Modeling Lab @ York University
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Augmented Urban Space Modeling Lab
location: York University, Toronto, Canada
permalink: pretty
